# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods
  pod 'Alamofire', '4.7.2'
  pod 'SwiftyJSON', '5.0.0'
  pod 'QRCodeReader.swift', '~> 10.1.0'
  pod 'RxSwift','~> 5.1.1'
  pod 'RxCocoa', '~> 5.1.1'
end

target 'AuditTrailClip' do
#  use_frameworks!
  
  common_pods
end

target 'ZorroSign' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for ZorroSign
  
  # Basic Pods
  common_pods
  pod 'ReCaptcha'
  pod 'ImageSlideshow/Kingfisher'
  
  # Google
  pod 'GoogleSignIn', '5.0.2'
  
  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  # Crashlytics
  pod 'Fabric', '~> 1.8.2'
  pod 'Crashlytics', '~> 3.11.1'
  
  #    pod 'IQKeyboardManagerSwift'
  pod 'IQKeyboardManagerSwift', '6.5.5'
  pod 'IHKeyboardAvoiding'
  pod 'ImageSlideshow'
  pod "RGSColorSlider"
  #pod 'SwiftAlertView', '~> 1.1'
  
  pod 'TagListView', '~> 1.0'
  
  pod 'Branch'
  pod 'FontAwesome.swift'
  pod 'ADCountryPicker', '~> 2.1.0'
  pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
  pod 'KJExpandableTableTree'
  pod 'p2.OAuth2'
  pod 'CropViewController'
  pod 'LUAutocompleteView'
  pod 'RappleProgressHUD'
end
